/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/precios': typeof PreciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/precios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/servicios/$slug'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/precios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/servicios/$slug'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/precios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/servicios/$slug'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  PreciosRoute: typeof PreciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  PreciosRoute: PreciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
